{
 "title": "Log Stats",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "log_message" },
   { "name": "os", "query": "ios, android" },
   { "name": "env", "query": "staging" },
   { "name": "app_prefix", "query": "rnapp" }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 4, "w": 17, "x": 0, "y": 0 }, "options": { "content": "# $__dashboard\n\n$log_message" } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": {
    "content": "### Time ranges\n- [now-2w..now](https://felmo.grafana.net/d/fef3xo6rzcao0a/log-context?from=now-2w&to=now)\n- [now-4w..now-2w](https://felmo.grafana.net/d/fef3xo6rzcao0a/log-context?from=now-4w&to=now-2w)\n- [now-6w..now-4w](https://felmo.grafana.net/d/fef3xo6rzcao0a/log-context?from=now-6w&to=now-4w)\n- [now-8w..now-6w](https://felmo.grafana.net/d/fef3xo6rzcao0a/log-context?from=now-8w&to=now-6w)"
   }
  },
  {
   "title": "Count (range)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({app=~\"($app_prefix)_($os)_$env\"} |= `$log_message` [$__range]))"
    }
   ]
  },
  {
   "title": "Count (week)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({app=~\"($app_prefix)_($os)_$env\"} |= `$log_message` [1w]))"
    }
   ]
  },
  {
   "title": "Count (month)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({project=~\"($app_prefix)_($os)_$env\"} |= `$log_message` [28d]))"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({app=~\"($app_prefix)_($os)_$env\"} |= `$log_message` [$__range]))"
    }
   ]
  },
  {
   "title": "Platforms",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({app=~\"($app_prefix)_android_$env\"} |= \"$log_message\" [$__auto]))",
     "legendFormat": "android"
    },
    {
     "direction": "backward",
     "expr": "sum(count_over_time({app=~\"($app_prefix)_ios_$env\"} |= \"$log_message\" [$__auto]))",
     "legendFormat": "ios"
    }
   ]
  },
  {
   "title": "Versions",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, sum by(version) (count_over_time({app=~\"($app_prefix)_($os)_$env\"} |= `$log_message` [$__auto])))"
    }
   ]
  },
  {
   "title": "Devices",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, sum by(runtime) (count_over_time({app=~\"($app_prefix)_($os)_$env\"} |= \"$log_message\" [$__auto])))"
    }
   ]
  },
  {
   "title": "Users",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, sum by(user_id) (count_over_time({app=~\"($app_prefix)_($os)_$env\"} |= \"$log_message\" [$__auto])))"
    }
   ]
  },
  {
   "title": "Logs sample",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=~\"($app_prefix)_($os)_$env\"} |= `$log_message`",
     "maxLines": 10
    }
   ]
  }
 ]
}